default: &default
  adapter: mysql2
  encoding: utf8
  pool: 15
  timeout: 30000
  host: localhost
  database: credit
  username: credit
  password: AvantLOC

development:
  <<: *default

test:
  <<: *default
  database: credit_test
  password: AvantLOC

production:
  <<: *default
  database: <%= ENV['PROD_DB_NAME'] %>
  username: <%= ENV['PROD_DB_USERNAME'] %>
  password: <%= ENV['PROD_DB_PASSWORD'] %>
